### ISSUE TITLE
Getting it into the ports tree ...

### ISSUE THREAD

**Issue by pmhausen** [freultwah/freebsd-acme-dns#1]
Hi!

Have you opened an issue with FreeBSD, already? If not, why not? Should I go ahead and do so?
Because that's the only way to get this into the official ports tree. Would be a shame if your good
and appreciated work wouldn't end up there, IMHO.

Kind regards,
Patrick

**Comment by freultwah** [comment]
If somebody else maintained it, why not. I don't know if I myself would have the time to shoulder such a responsibility.

**Comment by pmhausen** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263675
